# Generated by Django 5.1.6 on 2025-05-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_like_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_liked',
        ),
    ]
